### ISSUE TITLE
Syntax error while running

### ISSUE THREAD

**Issue by DivyangPDev** [mishakorzik/MailFinder#10]
SyntaxError: Non-UTF-8 code starting with '\xa7' in file /Users/divyangparmar/Documents/Personal/Projects/emailfinder/MailFinder/MailFinder.py on line 1, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

**Comment by mishakorzik** [comment]
You need to use python3.10 and view details on https://python.org/dev/peps/pep-0263/.
