### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\xa7'

### ISSUE THREAD

**Issue by spectator8** [mishakorzik/MailFinder#12]
SyntaxError: Non-UTF-8 code starting with '\xa7' in file d:\soft\git\MailFinder\MailFinder.py on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

**Comment by simonets4094** [comment]
謟ࠈ揟＂祰桴湯挭灡瑩污潣⵭⸰⸲⸱慴r㷭獭䣚戮徬䃻ི볈뀘抹ᓯ�ぜð㙎떷쥅b葝햤ᶋ훯�룟瞿枺䉆�쒆癱㌷ᢕ麞黩ặ䏔䏯㔅푦剅ꞙ㻻퇚᧺⯳櫥瘟粂⤌䈊߃⿲춾㵔ꬦ嫐监톥㞬촪㵈㜪㗇藥罌藝흋餩枆蚅멭劫굙閪ꟃ￮竍羝륧駳翾꤅朿忿롾ท㿳ﲞ�ﶂ㚯䵿ￚ녧헿ﶔ햯ꚓ陚ﾖ랛뷿䝮迯⟵￫ꎍﮣ翬岵翺令钂뎟翿닿℻쬽交ᕀ睺떾虘ꗤ諹쭔᫕⳩蜍≌ꅧ䌨꿪€岰墇夁齒�薑㡯鴡줕Ƛ뢔扳മ䅿⒋襴�輑Ǻ렠ꇗ㥡뎖ؠ脱ʊ訒�硹耔쑧Ȉ듗⠌첏㍜党㐧ꑂ뜷ᩬ鞐鋡莒삱砸装꣌⭡䎖巰諼嫜햠䡑᩼뺄扥䔙㥢ᶦ냍�奚ʂ뎢ަᐊԚː枬겑駜융쩏흅ᖶ謬晤텡凗餈昁Ḳ넖蜝侮樂૛悔뵁孙뗗っ畘ᤏਚԖ玘璻�墖㊁粏䠇虒猳斁ꢿ戙舎巏盛녯ꙩ쳫氬큑鑒밉긲ᯝ�◂룫吡垕ԁ균⪥՞썋즶ᔵ̌삺⍞᳕줟罃䉰냋賺빞⪙뿐짐灸礶趧퉴錝棡뛰ꩻ銟洃�訏巤牷렱ႚᢀﵩ築㠲娣㷿퍹鿭褖﷾ꑰ잏つ멒쎗坞벇뽮믓쿶毉䀏뭽쒠䁤ꂐꨨ辫낱絋맔꾀꽮礻呟뫎㺓禖ᠶ贑딌ꓑ맛槪㈣᪼܍ᵣ鿈녂滽泿各䯴㾽腑ﴑ簭괋䏗詒ն᾵ﵡ杈簰從졌ꃅ꩷ᵫꙪ鳩㐔펪뫓䖗ꩲ橝㫧᫃⥀ԣ磁죭஻댝麐＆錺ꃮ춏೨鏺簑䈭䜫ғ巵걷褗醎朡솣入癁옂ᖀ砂鵽芗⚬褙ࠀ뽾腉哤竗홐鄘覱뀱崪ῥꤲﵲ깇泿ﾮꯔ揥ହ蛸ￇ㟃◧腰枃８騷嫍ﱾ꽟￸왙㓿昴框�⣂蘔⵱툂練諆좶溆न匐攒괜虖흿ᴢꈎంᆁ蓛써䂮혧돊㉩垔�ⴕ왹쨂號ឡິᜏᰰ꺏螺萰蚙ꭑ侔㜎殉ⷸᬶ鄒ꉓ쌫宲ᅄ飳脖ꃱ蛲�ﺺ栬疑萑葾觩ꂳ扬⁀岟ꅛ싩雸㢆覡㐺诱뇒㙡쵢ਭ묔씰灱갠ﳁ㪁䘰땮⧈ꆽ讶갌Ҩూ巆禢ྞ縙콏튵̨ШΘ᪭ן崡山㪠ả痒ೂ탸慷뗖⅚གፚ㌁攑杻伍綵헡�贘ㆽ箚ᱣ臯Ƒ삝알矄㳉䡊홻澵㣸妛벓杴䰑锳ﴑ눩䅀㱊䖿殾茣楎褐螖届룪ᆨ楡몁硣ᴈ쏡뷌扵Ⱝ솝ᖜᑵ祅兇⤃�윢쾝ጭ伧澭ꁸ〄᳙�ኟ䶝혺䕍圥抠䡆�⟈ᕀ껦߁쾕틸ࣈボঀ辫䘳㓃ၩᏄᭇ�Ꮠ确욿ᰩ᠖ۺ➛杓㥡鄸锫㪜ꚠ䰶ꄆ⮖駞힕퐆櫣寔晷Ḡ婷�㼰ʀ�螱蘓ꌲ㜫螋ꔹ酇傻὇ꨆ侄姒菈ᰮ쐆榀鼷ۊ뼰枷褸趵㇈銬三䵷쇃駜僫(褛쁅濄โ䂸貕뉩懞ꆘ䍵蒙攪䨂㌈䃿ૅ�☠쬈偡硖ᢇஶ䍒᩹㉎뛕鱜卶侘ᤃ蟟滂頭뭬দ釨鎇偰〦㽏⁅갗攳㐲ᑝ鼑䟫贳焀㜙ﭠ殌望䇫돨錵䢠狘ࠄ쾚藳ী鬔䍡唍栐賈㨎郀룎➔빫�쁂㥬倠䠯㢱䀴ⵐᓸ৔ႤГ獝絰쐷䄢ൟ冷藸ڐ䑐䓹䠾⇗宓璷谆膠ڇ♙ꑟ她팽ᅞ鏸ฦ恘ޭ旜膊５苈Ⱪꉢ邜☻䵟。萬쀺꠸⪧᭴�觀鱅댝撋⋡㆑廧빀潣嵀苨쌓꒬蝀⋞錖쾤蓔�粡ܽ䝚텽꼕ᶩꈯ䈰ഁ䊱잮څ삖㢳ȉ鬮化�팜얝㫫翟⟿ᘠ큨ꁻ훈胗ᐨꟸ伜풹�걛파嘄텥︕Ⳇ戊ￃ뤪㖂툜瀕ﰠ혫墙䠷攸஻㩜⪂恹톛茝䏸�絀Ḅ힔ⅰ፰Ά䔱袹⽹蛴ꉝ�㾻ଫ叻㺲䵈�ﰰ臮䓵졛鵸䏨㾬勻ᭇₖ罆陏马떽梲捗ତ㺝旳ᡙÏ䠇㜁㜍ᶆ壑ѧꃏザ姶ꚃ쫺냜渃짎늧兟Ⳏ㰟騆퀞ᒨ捏鹦毫Ṟ枔�㺿ꎟ턪ﳐ힃ᬆꐚ駺�ؖ麱㌂營걨ᒼｧ砪醓滸榨ࡶ츌蓢残ꎗ꥔ᛀ࠘䃌랛╫ଷ쭠揇ﮆￄ娼泌ᛯ�ꭏ㖹浌죑�尒鑐뎁엵腶職䢁ﯩ壒峯몍즥跠俞첋릊㐢랇嗀∗�ڇ榲�瀩�㜕Ӌ쎹楶䮙蜲肑ۃ노莧킒○䋒䤗⽹፞畍摕眎롫軖ǃᤧ␖㞣螐幊垒怪ᩦ슴⧆飄�ࣞ胍ￜ륿�鎓檓쯿뿵釃鶮櫪ￗ헪웪翾媳콿蒲陜쮐爒䉙䬮旈뤉ℬ▗다岄쮪爒鸍꫿깭哿﫤돏ﾬ㜴翏軕蹏൪ࢹⷴﾯ㎬鼎ﾤ៯퟿㞨㋊놛狿�늷�꺄휧ꗿ俽ￛ퓩걲㩰뵕⾻ﺲ켏泵꿿ᮖ礍퉙矜䑗洵✋홲茊좹摟邷㿳￩㶿�풨١ﴨ槿쿿쎝笧쟿翼ڭ鞊￷啇￩쾟叿娧컅蝟䕧으묋տ횸扭䖠鶼營ᵗ懗쯁ⵗ䂅킺厵㑽蛕ﴛ듽嶯ꓪ੍얙˺䒃랐棺É危�떯㺱᪽ヵ흯簍㱸쏗쪂Ə撼끨垼﬊젣亝鞺哺鿯܎ﻝꐥ迿퀔ഊﶻ⧳쎆⺍వ뺦쌏鲳ⅅ缮縼刀ၬ绵졾䘊ꖆ㙐Ŋ쏔︂ࢫ媚㎧왏ᇷꬕ䇾ഡᴽ紳甄㏐鮈▅㶴캟쾩钳ឧつ罺՟嚖먐巾㺖륆�䍯랾ꓜ蛑饬醓ῖ俹㘫෴〧웘빼莍樑杷㿐૫졵튵鵴ү螛熃脗问阆莠곰篸澁｝⠃㬙ቭ᭒톽퀧�콶吟豏ꉑ採壜똋呩ꍈꃯ᳞☿᰻兵癥ᛩ떾镖꽎Ϋ윗꟰鞋�쒇仝简롳⡏�鍩䗎쐏㽶貇峐ꃚ䡨ᡐ厫졶娈ƌ⽛쓑匉﫵㷪ᤚ⣸庈換ݖି餀잝띤⁎笨�솓憐柃㶂⍶ꓟ潎唀믆菉诂㯁븑俠炢녞绶턼夯笎맢䘓㉾�욮ᒼ峼❗숴젨ݗ孴ᨥḀ䙂㿺軴፸謿ﯢ﩯瞃烌잋좄料鮇팬뭏眠췠亟ؓ쥮М龊樟믽ᨍ홪♥ꤣ蓜�ꩰ㈳凬�岝躜瞴ጚ贈챛뎡뺫࿠꙱莗堾ퟵᙍ衂ѯ鎎၉䐟�屩Գ㮲㶎㹧㭯⮜뛑蹼嘁밍圢﹊㫻陚㪷뙔膧§ㆧ袘䖋힁輱鞺꾯捆鵶朊⩕嬣퇛嵨㹰푏䋲鴛㇫흃蓟㠏쟽磕ጒ罚鴓讫큗祰쿅�북櫱认邮ዎ鎣ａ챪ڬ␾쾏횸쿅슉页謥䝇܇ᰇ켅姞䣼渃王髣☾색鋐뇡䉱絩텂ꣵ➃唔蜳։殳貔᫸쐥⍜䛦ꕏ㫙뙄袴᦬ꩍ㼛ร㜒䙥ⓧ╞᥼筐컎ᑠ등ᅀ겣ᾧ鷨㵨萦縷贡ȶ彦�龈❽苊쥉达嶏鎴ꮡ츪빊镼䲅嘎㎴⪘�⦑址࿍請ఙ☜羷갩闏娔㚩섗訟옦忷倗癔�ナퟣ蹕☛乨�啜璉ꅃ鸳縔싌鱿퐆粌䰘�跁釻ꟳꁌ墤䙇灸唗鋯ᴝሊ懽뉊ꆠ遐럈缯烹₋Ქ씾鎣參䘡㘖�⼔髳骊湽엙ﲬ字댉㬣퓁晰実帇詒켰饸놔ຘ埯蘋胂ᨳⶸ흞󈆝흍震핒둽ᶤ㎛㚣봔荧ሄ⮂빟묵☊寚儮�ͩ整䲾搜缌鐚蛾닽蕑뱭♡閪늘-昛떨郝づ䵿᠚虅ꌉᨶ枕훤㷆시᪞蒛콅迟辙ነ⬮୍腉ϟ㞷윕ᥨ埉疭抣㙰掆凜ｩ(ᚯ윤롓暺簇휚ᶝ좴ꕁ㭚㞪잚欇ṙ㖈ⲉ䧀㱙↥ṱ돸탫糁퀞쀐ꥫ뚗ᩫ씶꠲䚓㔂藀㮊獼㸵뽍䈊᪟崫ꮌ蠶驗㯸렼듦췦宯ệ퍴絑჆藦ꀢ倁텧ொ艹縪凉꼊쒻䟱⣻聥ꠂ릂જ஖䫽瀄�ೇ踫ᄴ�ᵄꃺ쀄熳竨躁౑ꔔ車ꝷ軸瘷퐂൏�贯捀亴쫩쓕햒犖렒ﰞ셏煡଻ആ柬ؒ鎶뒧喓剢幐帰몜顑堑೚괤�돮氉垍팊얶�嬏徕䰶쨁蟰�惯Ъ帤땣ዣ븈﯐䅸吖ᩜ血姎ⷦ寧럴憵踛䢉뭙窜ꥑꤞ着ୠ嵵Ჭ廧빻뜻黂怛熅꙳Ζ䉈낭䪄㵃궩ﾕ䌁ම燨㝞媣꼀ᓇꂯ㮍ៅ筠ೞ심狷绹澦쮼뱰ü쮷坙஻厳⿇㳨혶㿮ꎽ붯ႇ㓑蝹톿龳튠鸣ﺢ螑槡ﯓ冚㘤ꆽ놾䆠첋㌬龍ೖ開ꌻ爭뫭䏤歶嬝觱톫鹎갂靚교ꩶ侊卸⩥氶茄鴞懑ﮚਰﴏꄝ睃栟ኌ핸옖舶ᨈ翐䍷菦㩔ꋣ퐄ᨉ巰ㅱ蕼ᕕ﬐ਰᇝ窑練栉뙳麀䱆庫ヲ�ⷂ퐼뜃冬곬칮啥�ﮞ鳙淐溇녎穁♃皼遊顙䡘Ａ냚씒綑鲅岟ᣍ�묉橈픏䉋ꕶ癡⒏芥䩟ỏ냚䋽蚪洭ΰ䖕縬溺鏄磹㞣฽㞎ꝷ읬⩶蚶朙명⺠ፏ쑟೤⚌띓姬寇姝엺描㱃俴듶ᇣᏂ枵㍳৽蛙ꝉ鋡픦ꗞ켧㷢囥筶ᇹ쒴㰡ᜂ㽘㊃淌ࣗ脟ќ컒懸烸硏涰ᓞ⊇ꢶ滏貮撯䰘㓅桖ꡏ䂪ꓼ૊淜藕睊톶仢䰻⤏䙺�Ꮙ挷㤻呅㚮짾⽦茢鳽鴋ዡ᭎⬔ㅧ୓Ｐ씖䏖럞᫗঳⩱�⛇욜�ᙂ챆ᣒ뒽럠╁猴�⬆曨醙䬙襯㆑풗郼〷憩훥鵵㖧ꦐ䦽踾됪ൄ絾�瑦苍㒢뽳㍇⃷回�쉩峜졺ᾒ䯾뛤댫洖滚띀꿛꯭묢䦮뛩累甾캔쉆闹繪잉릪鲃녏떄ꤞ᪲껿ꦆ筩냵큓퓤ퟥ୵휋䶝ୃҔ寝⥦멇�꣚�蛅賌혭뜻邺噳咠퀓厩ꥐ噶꓃筗꽎᪖公⾔䉢裤ꉥ쾢債᫷椓븯붚챈湅鰤᜶ㅏ縌痘턽堘翆߯뿣蚣ﾌ鯟�뱓嵐苓῀ﾉ횮릛삻閪ꪣ﷼᥷鷿ﾎ瘢Й귾脇䣋ᥭⶩ딣ꑥ貶雔�刲䙛쭪浈ꤙ⌭斵뚤풌醖㋚孒橆䣋ᥭⶩ딣ꑥ貶雔�刲䙛쭪浈ꤙ⌭ﾵ酈㋚圚棊祜坨돊㊼圚棊ᥜ⮍熣㑥貮闆룑鷒棈ᥜ⮍熣㑥貮闆룑ᨲ럷贖缫姿ￆ쵾�燲禹敿濼︦眗ᛉ鿷뇱ﾖ博﻾돳㢤ꁼ꽐ᯗ쟇뗇땆榥瓖秾꣙䛷魯칇쿿ﹾ雾뺞姮鎓翳ᡨ➰篢螺翛澚싟ⴴ뻺䛱ᙫ鿈䟩㍵㵒䬢┃⌎萩뎑樰�⬗８易苌誒⤥ὼ둽榜岥單乎੎鎲ｊﴯￜ꽑欴ￒｋ⇿澏﮹ﺬ郿⿿⮗ｹ浟ꓔ翿⒎못￴�퟿㚎翽突柿￱�뿻〪㿿휪辏ചᩩ憾쿿ꟳ糫⺕┖駋螻풟鯿﫵︃鲿﾿冫＇靟忾ￎﶤ칿ΌﾳﹲϿ翶蒼襗픽꿼泑ퟦꭿ☈翧郏椮챨킌봨纥컀膥ᗴᄌ酭�ቐ꘠쨤娸ಭ껿뺕褊蓱⭝퇃廱魉嗢ⱅ䛌点둗᧤풋䛵⬋䙜ⳗ㽎᭙�긤遅럣ӈ䡠楧∸䒧ᥱ䖹麔剥耧⾂Ꮋ෥쎽䖠䗖塚ӑּ㸥緞賈�䴊狗ഈ쫱梥깅ፃ⢿밝訐ঢ়⋔❝캤캌ᚈⳍ쮌괡㤖韥İ㉇ꊰࠒᠱ襷秦箾ꠃ嘭ٵeᢅ뛬ၝᗒׇ㎪凪嶶Ɯ﨟싮嘷歁怢ꈦ㤌뚩밯�ꌛ㞱獆豯㷣㈰Ꭰ돗籌瘷壓ꡚ颇돟綮럃遨礢컩鬢쨆ﺈ夔₠鸥⋟뗟䆑㒧細嶋妶룪ᆨ楡컂虆援衸芗�❛싖駒썥庻ꎷ쟷ꊺꎼ膨蒔褮眜뜾쭌掰럒ኁ�軒罴瑊㝘锕腜ᦊ뤡⍳셛唇♑搹㜄�ල臄఻ꔜ聁䃕뙂ꮁ뱫ಽఋ捽岆캦狂ᐨ⩛좕甹䵀艭䀾쳄쨩ͫ燪㮭揳둗蘒랂暹盱�凞愄㵇ᬘᲡ썬뻺⌵堤醺⌽�죂霱ꙴ毲䳜쇃駜⣕䣘戬8Ỗ죆腱ᄪ鉗൒傔䲥ी誜㈕䆱၌᎖蘢苭僔䂞䐲㳚ኊ㨉慃隷፭㓗㴁胲Δᓊ⫟疄䲦Ꚇ⊋畢䞝贳焀儥䃮࠼ࣽ㰕ረ锛А琍襦ী鬔䍡唍栐꿈쎈賨祋툫ѥ呝ؠ泉‹⽐녈㐸偀䔭퐔ꐉጐ䄔꓊蛯⑘ꯨ◁뼟툐言Ἠ㌼ᰃ�ꖺ怳〤ഇ帼曍寲廱콖垴︄覤ᘃ垘省抙애ֹ壓뉶�쵡㉧䋄�ɫ哵溅�ҝ㠛袱掳䁶酾尬㈤�젋ꠍ崋扰閘寐拄骙襰ᐻപ䃅꣫먯㗢况ᆅ栊ᖈ㵲㐮뛂㥔�덙㈔윶杴쮔㠛�ｿ‧栖篐袠ဆ¬Ყ륏⿔寜ಬӓ敖ᗑ웾ਬ썢⫿㖹苮ᰵᗒ⁰⯼駖㝘㡈럅논쥊껶羸絈帄汜띌䉡꘣ᜨ�䔰䮾紴敧罡䳂̄䧻ᛥ孄磈걃ȿ猨ꀡ몸歫텥욮ऋコ⯫뢮恩馇鵣峉봆䴆ᗵⅶ㌇�⢯陧䒹䪍㓱뺹뙡祎욆㧳ኪ촍牿摗쿒첄ザ頔軹捃ꗥטּ셗貛矄䵃䎳灠✖屜᲻Ὅ䪧똅ᷠ₌玛�銵֛톼䡆ḿ�︧퇧晢띻춨婾귍㚑橧弛驡㎲㊊뙰�『⤐濥䮟첋릊㐢чꤔᤌ㻽逴㍍龬❥試斛�鑡뭵체餥䣃懀밃폘䥁椒计벤꼗ꚉ⪺蜲떻먠瀎迣еꇤ힒롮闤頊뺙叁릩ੱ㝫봃䈷″ￗ﫤岟鏿翫껻跿圇躣嘾迃鏡ﾬ竕ﵮ嚯꨿쓺흈⽎畵匵硠礑瞪꒧埅零ꆍ㍛鿣刋ᶶ嘤鲶刮塶噱퍶蟊㔥滳匊྿揁뻰ౘ౺褮�宽﷈ꗿ響￦馷쿐￲꫍￴鋏坤뛿틿䯿⿿�︞㴿稥漣륿䟿መﴪ㏿帧坥ﺐ著ꗿ響￾｡ﻣ缿효뾔﻿⤬빵癖뿿ﾎ徟ￏ赯泿迖疪ၩ憾쿿腷留觢￺ﺃ⣿︿呯ﱥᾤ塠씷�䪏jjⱨ힦斑ᷣḋ蘲닧ⴢ狿￾챭᯿ﹲﴯ㿿틣�翽媵迎᯿歹쿿ﺑꟼ⣃࿰⶯햌ᆸ묱︊⅐⩡먐ᶮౠ㲇兇蟰蠷凫牁䢠ﰎ垃ࣄ糈翉٥�뎦푵త핋䜇슕ᦏ诲ᶘ慏ፃﰋ敪鬑⻘씰餔憞恾밿䏹蔡揰屑鴋泐瘗䴏䔖ꯧ컝汧쌇ጟ飄⧐ꧻ莁䱌�럈藛苽䖞碝䈄邻㺄症뇥旂鉷鴁颲盨摁汢︠䪲疼氇㞋੾≅䑁띌颋젾�⁾ꠢꍅⓍᜬ⚨薐䉇ப毫வ䖻Ꝕḱꠏ䍎ჯ벉렧�ꄗ⾱獂葟�툑龐䤓쨭嘥᎔Ⱅ낰聪╹낽㉌Ⓣ䲓줲錤㉌Ⓣ䲓줲錤㉌Ⓣ䲓줲錤㉌Ⓣ䲓줲錤㉌婽Ὼ퇣熵䀀

**Comment by mishakorzik** [comment]
Fixed
