### ISSUE TITLE
MainFinder.py file error

### ISSUE THREAD

**Issue by mingxin-yang** [mishakorzik/MailFinder#3]
~~~bash
$ python MailFinder.py
  File "MailFinder.py", line 4
    dZ
      dZ
        dZ
     ^
SyntaxError: invalid syntax
~~~

**Comment by mishakorzik** [comment]
Use python3

**Comment by mingxin-yang** [comment]
![image](https://user-images.githubusercontent.com/23076937/202508172-93328f72-0b37-41b8-bb53-491887ced316.png)
your MainFinder file is a binary file, the code cannot be seen in it, and it cannot be run directly with python.

**Comment by mingxin-yang** [comment]
![image](https://user-images.githubusercontent.com/23076937/202508855-70a09add-4eb9-4cca-bb71-758228a6a130.png)

@mishakorzik

**Comment by Dave181295** [comment]
Still the same issue, file is corrupted
