### ISSUE TITLE
Problem with running the tool throgh google clould shell

### ISSUE THREAD

**Issue by profesionalleet1337** [mishakorzik/MailFinder#6]
Hello, misha ! I wrote in Telegram, but for the moment don't get response.. 

I'm trying to use the tool through  google cloud shell, but when i type python MailFinder.py , the message i received is that :

SyntaxError: Non-UTF-8 code starting with '\xa7' in file /home/"name"/MailFinder/MailFinder.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Could you please advise what I need to do/clear or add to run the tool  from this platform?

**Comment by mishakorzik** [comment]
What is your python version?

**Comment by mishakorzik** [comment]
This issue has been closed as no response has been provided.

**Comment by profesionalleet1337** [comment]
Hey Misha, I'm following thread, I'm just not on github 24/7...
-> Tried again but still getting the same error 
Otherwise, I follow the instructions you wrote for the set-up.
As I said, I use it from Google Cloud Shell, I run quite a few different tools from there. I guess that will do too, I just don't know what command to put in exactly, to fix this ..
I checked the version I use through google cloud shell with the following command;
python3 --version -> and its said its this :  Python 3.9.2

The eror i get again when type python MailFinder.py is this :
    SyntaxError: Non-UTF-8 code starting with '\xa7' in file /home"johsmith123(hereismynameforexample)"/MailFinder/MailFinder.py on line 1, but no 
      encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by mishakorzik** [comment]
maybe try updating python to version 3.10

**Comment by profesionalleet1337** [comment]
Hello, i tried it with Kali . 
Getting this eror : Traceback (most recent call last):                                                                                                                                                                                                         
  File "MailFinder.py", line 1182, in <module>                                                                                                                                                                                             
  File "MailFinder.py", line 87, in selecttype                                                                                                                                                                                             
  File "MailFinder.py", line 648, in mailfinder 
  
  I saw , other user's have the same problem too ?

**Comment by mishakorzik** [comment]
Yes, this problem appeared recently, it is because email validation API is dead.

**Comment by profesionalleet1337** [comment]
I understand , but what this means ? That the tool won't work anymore ? Or will it be "upgraded" ?

**Comment by mishakorzik** [comment]
the tool will be updated later but i'm not sure
