### ISSUE TITLE
You probably shouldn't have hardcoded the API keys and compile the script into bytecode.

### ISSUE THREAD

**Issue by KOLANICH** [mishakorzik/MailFinder#7]
Also, :+1: for licensing this project under a license granting [the Four Freedoms](https://www.gnu.org/philosophy/free-sw.html).

**Comment by mishakorzik** [comment]
probably yes

**Comment by KOLANICH** [comment]
So, how about rewriting the history, replacing the bytecodde compiled file with its source code form? Also please keep in mind, the correct extension for bytecode is `pyc` for unoptimized bytecode and `pyo` for optimized one.

**Comment by KOLANICH** [comment]
And, BTW, your profile `README.md` contains dead links.
